//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AVLEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AVLEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_3.0}mspObject">
 *       &lt;sequence>
 *         &lt;element name="GMTTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="eventType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GPS" type="{http://www.multispeak.org/Version_3.0}GPS" minOccurs="0"/>
 *         &lt;element name="AVLAddress" type="{http://www.multispeak.org/Version_3.0}AVLAddress" minOccurs="0"/>
 *         &lt;element name="telemetry" type="{http://www.multispeak.org/Version_3.0}telemetry" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AVLEvent", propOrder = {
    "gmtTime",
    "eventType",
    "gps",
    "avlAddress",
    "telemetry"
})
public class AVLEvent
    extends MspObject
{

    @XmlElement(name = "GMTTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gmtTime;
    protected String eventType;
    @XmlElement(name = "GPS")
    protected GPS gps;
    @XmlElement(name = "AVLAddress")
    protected AVLAddress avlAddress;
    protected Telemetry telemetry;

    /**
     * Gets the value of the gmtTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGMTTime() {
        return gmtTime;
    }

    /**
     * Sets the value of the gmtTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGMTTime(XMLGregorianCalendar value) {
        this.gmtTime = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventType(String value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the gps property.
     * 
     * @return
     *     possible object is
     *     {@link GPS }
     *     
     */
    public GPS getGPS() {
        return gps;
    }

    /**
     * Sets the value of the gps property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPS }
     *     
     */
    public void setGPS(GPS value) {
        this.gps = value;
    }

    /**
     * Gets the value of the avlAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AVLAddress }
     *     
     */
    public AVLAddress getAVLAddress() {
        return avlAddress;
    }

    /**
     * Sets the value of the avlAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AVLAddress }
     *     
     */
    public void setAVLAddress(AVLAddress value) {
        this.avlAddress = value;
    }

    /**
     * Gets the value of the telemetry property.
     * 
     * @return
     *     possible object is
     *     {@link Telemetry }
     *     
     */
    public Telemetry getTelemetry() {
        return telemetry;
    }

    /**
     * Sets the value of the telemetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Telemetry }
     *     
     */
    public void setTelemetry(Telemetry value) {
        this.telemetry = value;
    }

}
