//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for billingDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="billingDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_3.0}mspObject">
 *       &lt;sequence>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="servLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="meterNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ppmLocationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="revenueMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="revenueYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cisBillDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="billingCycle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priorBalance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="payment" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="creditCharge" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="debitCharge" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="chargeItemList" type="{http://www.multispeak.org/Version_3.0}chargeItemList" minOccurs="0"/>
 *         &lt;element name="CISBalanceAfterBilling" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "billingDetail", propOrder = {
    "accountNumber",
    "serviceType",
    "servLoc",
    "meterNo",
    "ppmLocationID",
    "revenueMonth",
    "revenueYear",
    "cisBillDate",
    "billingCycle",
    "priorBalance",
    "payment",
    "creditCharge",
    "debitCharge",
    "chargeItemList",
    "cisBalanceAfterBilling"
})
public class BillingDetail
    extends MspObject
{

    protected String accountNumber;
    protected String serviceType;
    protected String servLoc;
    protected String meterNo;
    protected String ppmLocationID;
    protected String revenueMonth;
    protected String revenueYear;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cisBillDate;
    protected String billingCycle;
    protected Float priorBalance;
    protected Float payment;
    protected Float creditCharge;
    protected Float debitCharge;
    protected ChargeItemList chargeItemList;
    @XmlElement(name = "CISBalanceAfterBilling")
    protected Float cisBalanceAfterBilling;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the servLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServLoc() {
        return servLoc;
    }

    /**
     * Sets the value of the servLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServLoc(String value) {
        this.servLoc = value;
    }

    /**
     * Gets the value of the meterNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterNo() {
        return meterNo;
    }

    /**
     * Sets the value of the meterNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterNo(String value) {
        this.meterNo = value;
    }

    /**
     * Gets the value of the ppmLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpmLocationID() {
        return ppmLocationID;
    }

    /**
     * Sets the value of the ppmLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpmLocationID(String value) {
        this.ppmLocationID = value;
    }

    /**
     * Gets the value of the revenueMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueMonth() {
        return revenueMonth;
    }

    /**
     * Sets the value of the revenueMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueMonth(String value) {
        this.revenueMonth = value;
    }

    /**
     * Gets the value of the revenueYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueYear() {
        return revenueYear;
    }

    /**
     * Sets the value of the revenueYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueYear(String value) {
        this.revenueYear = value;
    }

    /**
     * Gets the value of the cisBillDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCisBillDate() {
        return cisBillDate;
    }

    /**
     * Sets the value of the cisBillDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCisBillDate(XMLGregorianCalendar value) {
        this.cisBillDate = value;
    }

    /**
     * Gets the value of the billingCycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCycle() {
        return billingCycle;
    }

    /**
     * Sets the value of the billingCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCycle(String value) {
        this.billingCycle = value;
    }

    /**
     * Gets the value of the priorBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPriorBalance() {
        return priorBalance;
    }

    /**
     * Sets the value of the priorBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPriorBalance(Float value) {
        this.priorBalance = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPayment(Float value) {
        this.payment = value;
    }

    /**
     * Gets the value of the creditCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCreditCharge() {
        return creditCharge;
    }

    /**
     * Sets the value of the creditCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCreditCharge(Float value) {
        this.creditCharge = value;
    }

    /**
     * Gets the value of the debitCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDebitCharge() {
        return debitCharge;
    }

    /**
     * Sets the value of the debitCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDebitCharge(Float value) {
        this.debitCharge = value;
    }

    /**
     * Gets the value of the chargeItemList property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeItemList }
     *     
     */
    public ChargeItemList getChargeItemList() {
        return chargeItemList;
    }

    /**
     * Sets the value of the chargeItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeItemList }
     *     
     */
    public void setChargeItemList(ChargeItemList value) {
        this.chargeItemList = value;
    }

    /**
     * Gets the value of the cisBalanceAfterBilling property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCISBalanceAfterBilling() {
        return cisBalanceAfterBilling;
    }

    /**
     * Sets the value of the cisBalanceAfterBilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCISBalanceAfterBilling(Float value) {
        this.cisBalanceAfterBilling = value;
    }

}
