//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gasMeter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gasMeter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_3.0}mspMeter">
 *       &lt;sequence>
 *         &lt;element name="gasNameplate" type="{http://www.multispeak.org/Version_3.0}gasNameplate" minOccurs="0"/>
 *         &lt;element name="gasUtilityInfo" type="{http://www.multispeak.org/Version_3.0}gasUtilityInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gasMeter", propOrder = {
    "gasNameplate",
    "gasUtilityInfo"
})
public class GasMeter
    extends MspMeter
{

    protected GasNameplate gasNameplate;
    protected GasUtilityInfo gasUtilityInfo;

    /**
     * Gets the value of the gasNameplate property.
     * 
     * @return
     *     possible object is
     *     {@link GasNameplate }
     *     
     */
    public GasNameplate getGasNameplate() {
        return gasNameplate;
    }

    /**
     * Sets the value of the gasNameplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasNameplate }
     *     
     */
    public void setGasNameplate(GasNameplate value) {
        this.gasNameplate = value;
    }

    /**
     * Gets the value of the gasUtilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GasUtilityInfo }
     *     
     */
    public GasUtilityInfo getGasUtilityInfo() {
        return gasUtilityInfo;
    }

    /**
     * Sets the value of the gasUtilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasUtilityInfo }
     *     
     */
    public void setGasUtilityInfo(GasUtilityInfo value) {
        this.gasUtilityInfo = value;
    }

}
