//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for meter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="meter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_3.0}mspDevice">
 *       &lt;sequence>
 *         &lt;element name="meterNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="meterType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sealNumberList" type="{http://www.multispeak.org/Version_3.0}ArrayOfString2" minOccurs="0"/>
 *         &lt;element name="AMRType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMRDeviceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMRVendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameplate" type="{http://www.multispeak.org/Version_3.0}nameplate" minOccurs="0"/>
 *         &lt;element name="utilityInfo" type="{http://www.multispeak.org/Version_3.0}utilityInfo" minOccurs="0"/>
 *         &lt;element name="moduleList" type="{http://www.multispeak.org/Version_3.0}moduleList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "meter", propOrder = {
    "meterNo",
    "serialNumber",
    "meterType",
    "manufacturer",
    "sealNumberList",
    "amrType",
    "amrDeviceType",
    "amrVendor",
    "nameplate",
    "utilityInfo",
    "moduleList"
})
public class Meter
    extends MspDevice
{

    protected String meterNo;
    protected String serialNumber;
    protected String meterType;
    protected String manufacturer;
    protected ArrayOfString2 sealNumberList;
    @XmlElement(name = "AMRType")
    protected String amrType;
    @XmlElement(name = "AMRDeviceType")
    protected String amrDeviceType;
    @XmlElement(name = "AMRVendor")
    protected String amrVendor;
    protected Nameplate nameplate;
    protected UtilityInfo utilityInfo;
    protected ModuleList moduleList;

    /**
     * Gets the value of the meterNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterNo() {
        return meterNo;
    }

    /**
     * Sets the value of the meterNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterNo(String value) {
        this.meterNo = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the meterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterType() {
        return meterType;
    }

    /**
     * Sets the value of the meterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterType(String value) {
        this.meterType = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the sealNumberList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString2 }
     *     
     */
    public ArrayOfString2 getSealNumberList() {
        return sealNumberList;
    }

    /**
     * Sets the value of the sealNumberList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString2 }
     *     
     */
    public void setSealNumberList(ArrayOfString2 value) {
        this.sealNumberList = value;
    }

    /**
     * Gets the value of the amrType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMRType() {
        return amrType;
    }

    /**
     * Sets the value of the amrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMRType(String value) {
        this.amrType = value;
    }

    /**
     * Gets the value of the amrDeviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMRDeviceType() {
        return amrDeviceType;
    }

    /**
     * Sets the value of the amrDeviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMRDeviceType(String value) {
        this.amrDeviceType = value;
    }

    /**
     * Gets the value of the amrVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMRVendor() {
        return amrVendor;
    }

    /**
     * Sets the value of the amrVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMRVendor(String value) {
        this.amrVendor = value;
    }

    /**
     * Gets the value of the nameplate property.
     * 
     * @return
     *     possible object is
     *     {@link Nameplate }
     *     
     */
    public Nameplate getNameplate() {
        return nameplate;
    }

    /**
     * Sets the value of the nameplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nameplate }
     *     
     */
    public void setNameplate(Nameplate value) {
        this.nameplate = value;
    }

    /**
     * Gets the value of the utilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UtilityInfo }
     *     
     */
    public UtilityInfo getUtilityInfo() {
        return utilityInfo;
    }

    /**
     * Sets the value of the utilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UtilityInfo }
     *     
     */
    public void setUtilityInfo(UtilityInfo value) {
        this.utilityInfo = value;
    }

    /**
     * Gets the value of the moduleList property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleList }
     *     
     */
    public ModuleList getModuleList() {
        return moduleList;
    }

    /**
     * Sets the value of the moduleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleList }
     *     
     */
    public void setModuleList(ModuleList value) {
        this.moduleList = value;
    }

}
