//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mspSwitchDeviceList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mspSwitchDeviceList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="mspOverCurrentDevice" type="{http://www.multispeak.org/Version_3.0}mspOverCurrentDevice" minOccurs="0"/>
 *           &lt;element name="switch" type="{http://www.multispeak.org/Version_3.0}mspSwitchingDevice" minOccurs="0"/>
 *           &lt;element name="mspSwitchingDevice" type="{http://www.multispeak.org/Version_3.0}mspSwitchingDevice" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mspSwitchDeviceList", propOrder = {
    "mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice"
})
public class MspSwitchDeviceList {

    @XmlElementRefs({
        @XmlElementRef(name = "mspSwitchingDevice", namespace = "http://www.multispeak.org/Version_3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mspOverCurrentDevice", namespace = "http://www.multispeak.org/Version_3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "switch", namespace = "http://www.multispeak.org/Version_3.0", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends MspSwitchingDevice>> mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice;

    /**
     * Gets the value of the mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMspOverCurrentDeviceOrSwitchOrMspSwitchingDevice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link MspSwitchingDevice }{@code >}
     * {@link JAXBElement }{@code <}{@link MspSwitchingDevice }{@code >}
     * {@link JAXBElement }{@code <}{@link MspOverCurrentDevice }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends MspSwitchingDevice>> getMspOverCurrentDeviceOrSwitchOrMspSwitchingDevice() {
        if (mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice == null) {
            mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice = new ArrayList<JAXBElement<? extends MspSwitchingDevice>>();
        }
        return this.mspOverCurrentDeviceOrSwitchOrMspSwitchingDevice;
    }

}
