//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.partnersoft.v5.soap.service.example.multispeak.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MultiSpeakMsgHeader_QNAME = new QName("http://www.multispeak.org/Version_3.0", "MultiSpeakMsgHeader");
    private final static QName _MspConnectivityPointParentSectionID_QNAME = new QName("http://www.multispeak.org/Version_3.0", "parentSectionID");
    private final static QName _MspConnectivityPointToNodeID_QNAME = new QName("http://www.multispeak.org/Version_3.0", "toNodeID");
    private final static QName _MspConnectivityPointSectionID_QNAME = new QName("http://www.multispeak.org/Version_3.0", "sectionID");
    private final static QName _MspConnectivityPointFromNodeID_QNAME = new QName("http://www.multispeak.org/Version_3.0", "fromNodeID");
    private final static QName _EndDeviceShipmentReceivedModules_QNAME = new QName("http://www.multispeak.org/Version_3.0", "receivedModules");
    private final static QName _EndDeviceShipmentPoReferenceNumber_QNAME = new QName("http://www.multispeak.org/Version_3.0", "poReferenceNumber");
    private final static QName _EndDeviceShipmentShippingTicketNumber_QNAME = new QName("http://www.multispeak.org/Version_3.0", "shippingTicketNumber");
    private final static QName _EndDeviceShipmentReceivedMeters_QNAME = new QName("http://www.multispeak.org/Version_3.0", "receivedMeters");
    private final static QName _EndDeviceShipmentRecipient_QNAME = new QName("http://www.multispeak.org/Version_3.0", "recipient");
    private final static QName _EndDeviceShipmentShippedToAddress_QNAME = new QName("http://www.multispeak.org/Version_3.0", "shippedToAddress");
    private final static QName _EndDeviceShipmentUtility_QNAME = new QName("http://www.multispeak.org/Version_3.0", "utility");
    private final static QName _EndDeviceShipmentTransponderIDRange_QNAME = new QName("http://www.multispeak.org/Version_3.0", "transponderIDRange");
    private final static QName _EndDeviceShipmentReceivedCDDevices_QNAME = new QName("http://www.multispeak.org/Version_3.0", "receivedCDDevices");
    private final static QName _EndDeviceShipmentReceivedLoadManagementDevices_QNAME = new QName("http://www.multispeak.org/Version_3.0", "receivedLoadManagementDevices");
    private final static QName _EndDeviceShipmentShippedDate_QNAME = new QName("http://www.multispeak.org/Version_3.0", "shippedDate");
    private final static QName _EndDeviceShipmentManufacturer_QNAME = new QName("http://www.multispeak.org/Version_3.0", "manufacturer");
    private final static QName _StatusClockForward_QNAME = new QName("http://www.multispeak.org/Version_3.0", "clockForward");
    private final static QName _StatusTestData_QNAME = new QName("http://www.multispeak.org/Version_3.0", "testData");
    private final static QName _StatusRecorderStopped_QNAME = new QName("http://www.multispeak.org/Version_3.0", "recorderStopped");
    private final static QName _StatusDSTinEffect_QNAME = new QName("http://www.multispeak.org/Version_3.0", "DSTinEffect");
    private final static QName _StatusOverflow_QNAME = new QName("http://www.multispeak.org/Version_3.0", "overflow");
    private final static QName _StatusInvalid_QNAME = new QName("http://www.multispeak.org/Version_3.0", "invalid");
    private final static QName _StatusConfigChanged_QNAME = new QName("http://www.multispeak.org/Version_3.0", "configChanged");
    private final static QName _StatusManuallyModified_QNAME = new QName("http://www.multispeak.org/Version_3.0", "manuallyModified");
    private final static QName _StatusClockBackward_QNAME = new QName("http://www.multispeak.org/Version_3.0", "clockBackward");
    private final static QName _StatusManuallyEntered_QNAME = new QName("http://www.multispeak.org/Version_3.0", "manuallyEntered");
    private final static QName _StatusPartialInterval_QNAME = new QName("http://www.multispeak.org/Version_3.0", "partialInterval");
    private final static QName _StatusLongInterval_QNAME = new QName("http://www.multispeak.org/Version_3.0", "longInterval");
    private final static QName _MspSwitchDeviceListMspSwitchingDevice_QNAME = new QName("http://www.multispeak.org/Version_3.0", "mspSwitchingDevice");
    private final static QName _MspSwitchDeviceListMspOverCurrentDevice_QNAME = new QName("http://www.multispeak.org/Version_3.0", "mspOverCurrentDevice");
    private final static QName _MspSwitchDeviceListSwitch_QNAME = new QName("http://www.multispeak.org/Version_3.0", "switch");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.partnersoft.v5.soap.service.example.multispeak.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MeterBase }
     * 
     */
    public MeterBase createMeterBase() {
        return new MeterBase();
    }

    /**
     * Create an instance of {@link MeterBase.DeviceList }
     * 
     */
    public MeterBase.DeviceList createMeterBaseDeviceList() {
        return new MeterBase.DeviceList();
    }

    /**
     * Create an instance of {@link EndDeviceShipment }
     * 
     */
    public EndDeviceShipment createEndDeviceShipment() {
        return new EndDeviceShipment();
    }

    /**
     * Create an instance of {@link Meters }
     * 
     */
    public Meters createMeters() {
        return new Meters();
    }

    /**
     * Create an instance of {@link SubstationLoadControlStatus }
     * 
     */
    public SubstationLoadControlStatus createSubstationLoadControlStatus() {
        return new SubstationLoadControlStatus();
    }

    /**
     * Create an instance of {@link SubstationLoadControlStatus.ControlledItems }
     * 
     */
    public SubstationLoadControlStatus.ControlledItems createSubstationLoadControlStatusControlledItems() {
        return new SubstationLoadControlStatus.ControlledItems();
    }

    /**
     * Create an instance of {@link LoadManagementEvent }
     * 
     */
    public LoadManagementEvent createLoadManagementEvent() {
        return new LoadManagementEvent();
    }

    /**
     * Create an instance of {@link LoadManagementEvent.Strategy }
     * 
     */
    public LoadManagementEvent.Strategy createLoadManagementEventStrategy() {
        return new LoadManagementEvent.Strategy();
    }

    /**
     * Create an instance of {@link com.partnersoft.v5.soap.service.example.multispeak.model.OutageCustomer }
     * 
     */
    public com.partnersoft.v5.soap.service.example.multispeak.model.OutageCustomer createOutageCustomer() {
        return new com.partnersoft.v5.soap.service.example.multispeak.model.OutageCustomer();
    }

    /**
     * Create an instance of {@link ServiceLocation }
     * 
     */
    public ServiceLocation createServiceLocation() {
        return new ServiceLocation();
    }

    /**
     * Create an instance of {@link Premise }
     * 
     */
    public Premise createPremise() {
        return new Premise();
    }

    /**
     * Create an instance of {@link ServiceLocations }
     * 
     */
    public ServiceLocations createServiceLocations() {
        return new ServiceLocations();
    }

    /**
     * Create an instance of {@link MeterRead }
     * 
     */
    public MeterRead createMeterRead() {
        return new MeterRead();
    }

    /**
     * Create an instance of {@link PayableItemList }
     * 
     */
    public PayableItemList createPayableItemList() {
        return new PayableItemList();
    }

    /**
     * Create an instance of {@link GasNameplate }
     * 
     */
    public GasNameplate createGasNameplate() {
        return new GasNameplate();
    }

    /**
     * Create an instance of {@link LinkedTransformer }
     * 
     */
    public LinkedTransformer createLinkedTransformer() {
        return new LinkedTransformer();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link ArrayOfOutageCustomerListOutageCustomer }
     * 
     */
    public ArrayOfOutageCustomerListOutageCustomer createArrayOfOutageCustomerListOutageCustomer() {
        return new ArrayOfOutageCustomerListOutageCustomer();
    }

    /**
     * Create an instance of {@link GetWorkOrdersByStatusResponse }
     * 
     */
    public GetWorkOrdersByStatusResponse createGetWorkOrdersByStatusResponse() {
        return new GetWorkOrdersByStatusResponse();
    }

    /**
     * Create an instance of {@link ArrayOfWorkOrder }
     * 
     */
    public ArrayOfWorkOrder createArrayOfWorkOrder() {
        return new ArrayOfWorkOrder();
    }

    /**
     * Create an instance of {@link MaterialManagementAssemblyNotificationResponse }
     * 
     */
    public MaterialManagementAssemblyNotificationResponse createMaterialManagementAssemblyNotificationResponse() {
        return new MaterialManagementAssemblyNotificationResponse();
    }

    /**
     * Create an instance of {@link ArrayOfErrorObject }
     * 
     */
    public ArrayOfErrorObject createArrayOfErrorObject() {
        return new ArrayOfErrorObject();
    }

    /**
     * Create an instance of {@link ReturnGeneratedNumberResponse }
     * 
     */
    public ReturnGeneratedNumberResponse createReturnGeneratedNumberResponse() {
        return new ReturnGeneratedNumberResponse();
    }

    /**
     * Create an instance of {@link ErrorObject }
     * 
     */
    public ErrorObject createErrorObject() {
        return new ErrorObject();
    }

    /**
     * Create an instance of {@link GetWorkOrdersByWorkOrderNumberResponse }
     * 
     */
    public GetWorkOrdersByWorkOrderNumberResponse createGetWorkOrdersByWorkOrderNumberResponse() {
        return new GetWorkOrdersByWorkOrderNumberResponse();
    }

    /**
     * Create an instance of {@link GetMethods }
     * 
     */
    public GetMethods createGetMethods() {
        return new GetMethods();
    }

    /**
     * Create an instance of {@link GetAllMaterialItems }
     * 
     */
    public GetAllMaterialItems createGetAllMaterialItems() {
        return new GetAllMaterialItems();
    }

    /**
     * Create an instance of {@link GetDomainNames }
     * 
     */
    public GetDomainNames createGetDomainNames() {
        return new GetDomainNames();
    }

    /**
     * Create an instance of {@link GetModifiedMaterialItemsResponse }
     * 
     */
    public GetModifiedMaterialItemsResponse createGetModifiedMaterialItemsResponse() {
        return new GetModifiedMaterialItemsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfMaterialItem }
     * 
     */
    public ArrayOfMaterialItem createArrayOfMaterialItem() {
        return new ArrayOfMaterialItem();
    }

    /**
     * Create an instance of {@link GetDomainMembersResponse }
     * 
     */
    public GetDomainMembersResponse createGetDomainMembersResponse() {
        return new GetDomainMembersResponse();
    }

    /**
     * Create an instance of {@link ArrayOfDomainMember }
     * 
     */
    public ArrayOfDomainMember createArrayOfDomainMember() {
        return new ArrayOfDomainMember();
    }

    /**
     * Create an instance of {@link GetWorkOrderSelectionByStatusResponse }
     * 
     */
    public GetWorkOrderSelectionByStatusResponse createGetWorkOrderSelectionByStatusResponse() {
        return new GetWorkOrderSelectionByStatusResponse();
    }

    /**
     * Create an instance of {@link ArrayOfWorkOrderSelection }
     * 
     */
    public ArrayOfWorkOrderSelection createArrayOfWorkOrderSelection() {
        return new ArrayOfWorkOrderSelection();
    }

    /**
     * Create an instance of {@link GetWorkOrdersByWorkOrderNumber }
     * 
     */
    public GetWorkOrdersByWorkOrderNumber createGetWorkOrdersByWorkOrderNumber() {
        return new GetWorkOrdersByWorkOrderNumber();
    }

    /**
     * Create an instance of {@link PingURL }
     * 
     */
    public PingURL createPingURL() {
        return new PingURL();
    }

    /**
     * Create an instance of {@link MultiSpeakMsgHeader }
     * 
     */
    public MultiSpeakMsgHeader createMultiSpeakMsgHeader() {
        return new MultiSpeakMsgHeader();
    }

    /**
     * Create an instance of {@link GetModifiedMaterialManagementAssemblies }
     * 
     */
    public GetModifiedMaterialManagementAssemblies createGetModifiedMaterialManagementAssemblies() {
        return new GetModifiedMaterialManagementAssemblies();
    }

    /**
     * Create an instance of {@link StakedWorkOrderNotification }
     * 
     */
    public StakedWorkOrderNotification createStakedWorkOrderNotification() {
        return new StakedWorkOrderNotification();
    }

    /**
     * Create an instance of {@link GetAllMaterialItemsResponse }
     * 
     */
    public GetAllMaterialItemsResponse createGetAllMaterialItemsResponse() {
        return new GetAllMaterialItemsResponse();
    }

    /**
     * Create an instance of {@link GetModifiedMaterialManagementAssembliesResponse }
     * 
     */
    public GetModifiedMaterialManagementAssembliesResponse createGetModifiedMaterialManagementAssembliesResponse() {
        return new GetModifiedMaterialManagementAssembliesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfMaterialManagementAssembly }
     * 
     */
    public ArrayOfMaterialManagementAssembly createArrayOfMaterialManagementAssembly() {
        return new ArrayOfMaterialManagementAssembly();
    }

    /**
     * Create an instance of {@link UpdateWO }
     * 
     */
    public UpdateWO createUpdateWO() {
        return new UpdateWO();
    }

    /**
     * Create an instance of {@link ArrayOfExtensionsItem }
     * 
     */
    public ArrayOfExtensionsItem createArrayOfExtensionsItem() {
        return new ArrayOfExtensionsItem();
    }

    /**
     * Create an instance of {@link GetWorkOrderSelectionListResponse }
     * 
     */
    public GetWorkOrderSelectionListResponse createGetWorkOrderSelectionListResponse() {
        return new GetWorkOrderSelectionListResponse();
    }

    /**
     * Create an instance of {@link GetModifiedMaterialItems }
     * 
     */
    public GetModifiedMaterialItems createGetModifiedMaterialItems() {
        return new GetModifiedMaterialItems();
    }

    /**
     * Create an instance of {@link GetWorkOrderSelectionList }
     * 
     */
    public GetWorkOrderSelectionList createGetWorkOrderSelectionList() {
        return new GetWorkOrderSelectionList();
    }

    /**
     * Create an instance of {@link ReturnGeneratedNumber }
     * 
     */
    public ReturnGeneratedNumber createReturnGeneratedNumber() {
        return new ReturnGeneratedNumber();
    }

    /**
     * Create an instance of {@link RequestedNumber }
     * 
     */
    public RequestedNumber createRequestedNumber() {
        return new RequestedNumber();
    }

    /**
     * Create an instance of {@link GetNextNumberResponse }
     * 
     */
    public GetNextNumberResponse createGetNextNumberResponse() {
        return new GetNextNumberResponse();
    }

    /**
     * Create an instance of {@link StakedWorkOrderNotificationResponse }
     * 
     */
    public StakedWorkOrderNotificationResponse createStakedWorkOrderNotificationResponse() {
        return new StakedWorkOrderNotificationResponse();
    }

    /**
     * Create an instance of {@link GetWorkOrderSelectionByStatus }
     * 
     */
    public GetWorkOrderSelectionByStatus createGetWorkOrderSelectionByStatus() {
        return new GetWorkOrderSelectionByStatus();
    }

    /**
     * Create an instance of {@link UpdateWOResponse }
     * 
     */
    public UpdateWOResponse createUpdateWOResponse() {
        return new UpdateWOResponse();
    }

    /**
     * Create an instance of {@link GetMethodsResponse }
     * 
     */
    public GetMethodsResponse createGetMethodsResponse() {
        return new GetMethodsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link GetDomainMembers }
     * 
     */
    public GetDomainMembers createGetDomainMembers() {
        return new GetDomainMembers();
    }

    /**
     * Create an instance of {@link GetWorkOrdersByStatus }
     * 
     */
    public GetWorkOrdersByStatus createGetWorkOrdersByStatus() {
        return new GetWorkOrdersByStatus();
    }

    /**
     * Create an instance of {@link PingURLResponse }
     * 
     */
    public PingURLResponse createPingURLResponse() {
        return new PingURLResponse();
    }

    /**
     * Create an instance of {@link GetNextNumber }
     * 
     */
    public GetNextNumber createGetNextNumber() {
        return new GetNextNumber();
    }

    /**
     * Create an instance of {@link ExtensionsList }
     * 
     */
    public ExtensionsList createExtensionsList() {
        return new ExtensionsList();
    }

    /**
     * Create an instance of {@link MaterialManagementAssemblyNotification }
     * 
     */
    public MaterialManagementAssemblyNotification createMaterialManagementAssemblyNotification() {
        return new MaterialManagementAssemblyNotification();
    }

    /**
     * Create an instance of {@link GetAllMaterialManagementAssemblies }
     * 
     */
    public GetAllMaterialManagementAssemblies createGetAllMaterialManagementAssemblies() {
        return new GetAllMaterialManagementAssemblies();
    }

    /**
     * Create an instance of {@link GetAllMaterialManagementAssembliesResponse }
     * 
     */
    public GetAllMaterialManagementAssembliesResponse createGetAllMaterialManagementAssembliesResponse() {
        return new GetAllMaterialManagementAssembliesResponse();
    }

    /**
     * Create an instance of {@link GetDomainNamesResponse }
     * 
     */
    public GetDomainNamesResponse createGetDomainNamesResponse() {
        return new GetDomainNamesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTransformer }
     * 
     */
    public ArrayOfTransformer createArrayOfTransformer() {
        return new ArrayOfTransformer();
    }

    /**
     * Create an instance of {@link LMDeviceExchange }
     * 
     */
    public LMDeviceExchange createLMDeviceExchange() {
        return new LMDeviceExchange();
    }

    /**
     * Create an instance of {@link BoxType }
     * 
     */
    public BoxType createBoxType() {
        return new BoxType();
    }

    /**
     * Create an instance of {@link ArrayOfEmployeeTimeRecord }
     * 
     */
    public ArrayOfEmployeeTimeRecord createArrayOfEmployeeTimeRecord() {
        return new ArrayOfEmployeeTimeRecord();
    }

    /**
     * Create an instance of {@link ProfileType }
     * 
     */
    public ProfileType createProfileType() {
        return new ProfileType();
    }

    /**
     * Create an instance of {@link TransformerBank }
     * 
     */
    public TransformerBank createTransformerBank() {
        return new TransformerBank();
    }

    /**
     * Create an instance of {@link AdjustmentItemList }
     * 
     */
    public AdjustmentItemList createAdjustmentItemList() {
        return new AdjustmentItemList();
    }

    /**
     * Create an instance of {@link PpmMeterExchange }
     * 
     */
    public PpmMeterExchange createPpmMeterExchange() {
        return new PpmMeterExchange();
    }

    /**
     * Create an instance of {@link PcbTestList }
     * 
     */
    public PcbTestList createPcbTestList() {
        return new PcbTestList();
    }

    /**
     * Create an instance of {@link JointUse }
     * 
     */
    public JointUse createJointUse() {
        return new JointUse();
    }

    /**
     * Create an instance of {@link FixedCharge }
     * 
     */
    public FixedCharge createFixedCharge() {
        return new FixedCharge();
    }

    /**
     * Create an instance of {@link AdjustmentItem }
     * 
     */
    public AdjustmentItem createAdjustmentItem() {
        return new AdjustmentItem();
    }

    /**
     * Create an instance of {@link OutageEventStatus }
     * 
     */
    public OutageEventStatus createOutageEventStatus() {
        return new OutageEventStatus();
    }

    /**
     * Create an instance of {@link TransformerRatio }
     * 
     */
    public TransformerRatio createTransformerRatio() {
        return new TransformerRatio();
    }

    /**
     * Create an instance of {@link LoadFlowResult }
     * 
     */
    public LoadFlowResult createLoadFlowResult() {
        return new LoadFlowResult();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link ArrayOfJointUse }
     * 
     */
    public ArrayOfJointUse createArrayOfJointUse() {
        return new ArrayOfJointUse();
    }

    /**
     * Create an instance of {@link OhSecondaryLine }
     * 
     */
    public OhSecondaryLine createOhSecondaryLine() {
        return new OhSecondaryLine();
    }

    /**
     * Create an instance of {@link PropaneNameplate }
     * 
     */
    public PropaneNameplate createPropaneNameplate() {
        return new PropaneNameplate();
    }

    /**
     * Create an instance of {@link OutageLocation }
     * 
     */
    public OutageLocation createOutageLocation() {
        return new OutageLocation();
    }

    /**
     * Create an instance of {@link ArrayOfCPR }
     * 
     */
    public ArrayOfCPR createArrayOfCPR() {
        return new ArrayOfCPR();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link UtilityInfo }
     * 
     */
    public UtilityInfo createUtilityInfo() {
        return new UtilityInfo();
    }

    /**
     * Create an instance of {@link ScadaPoint }
     * 
     */
    public ScadaPoint createScadaPoint() {
        return new ScadaPoint();
    }

    /**
     * Create an instance of {@link ArrayOfString1 }
     * 
     */
    public ArrayOfString1 createArrayOfString1() {
        return new ArrayOfString1();
    }

    /**
     * Create an instance of {@link ArrayOfString2 }
     * 
     */
    public ArrayOfString2 createArrayOfString2() {
        return new ArrayOfString2();
    }

    /**
     * Create an instance of {@link ArrayOfStation }
     * 
     */
    public ArrayOfStation createArrayOfStation() {
        return new ArrayOfStation();
    }

    /**
     * Create an instance of {@link PpmTransaction }
     * 
     */
    public PpmTransaction createPpmTransaction() {
        return new PpmTransaction();
    }

    /**
     * Create an instance of {@link ElectricMeter }
     * 
     */
    public ElectricMeter createElectricMeter() {
        return new ElectricMeter();
    }

    /**
     * Create an instance of {@link CDCustomer }
     * 
     */
    public CDCustomer createCDCustomer() {
        return new CDCustomer();
    }

    /**
     * Create an instance of {@link MspDeviceExchange }
     * 
     */
    public MspDeviceExchange createMspDeviceExchange() {
        return new MspDeviceExchange();
    }

    /**
     * Create an instance of {@link Motor }
     * 
     */
    public Motor createMotor() {
        return new Motor();
    }

    /**
     * Create an instance of {@link PrimaryCabinet }
     * 
     */
    public PrimaryCabinet createPrimaryCabinet() {
        return new PrimaryCabinet();
    }

    /**
     * Create an instance of {@link BackgroundGraphics }
     * 
     */
    public BackgroundGraphics createBackgroundGraphics() {
        return new BackgroundGraphics();
    }

    /**
     * Create an instance of {@link AllocatedLoad }
     * 
     */
    public AllocatedLoad createAllocatedLoad() {
        return new AllocatedLoad();
    }

    /**
     * Create an instance of {@link ChargeableDevice }
     * 
     */
    public ChargeableDevice createChargeableDevice() {
        return new ChargeableDevice();
    }

    /**
     * Create an instance of {@link ReadingObject }
     * 
     */
    public ReadingObject createReadingObject() {
        return new ReadingObject();
    }

    /**
     * Create an instance of {@link UsageItem }
     * 
     */
    public UsageItem createUsageItem() {
        return new UsageItem();
    }

    /**
     * Create an instance of {@link MaterialManagementAssembly }
     * 
     */
    public MaterialManagementAssembly createMaterialManagementAssembly() {
        return new MaterialManagementAssembly();
    }

    /**
     * Create an instance of {@link GenericLineFeature }
     * 
     */
    public GenericLineFeature createGenericLineFeature() {
        return new GenericLineFeature();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link CumDemand }
     * 
     */
    public CumDemand createCumDemand() {
        return new CumDemand();
    }

    /**
     * Create an instance of {@link ArrayOfMeasurementType }
     * 
     */
    public ArrayOfMeasurementType createArrayOfMeasurementType() {
        return new ArrayOfMeasurementType();
    }

    /**
     * Create an instance of {@link Assembly }
     * 
     */
    public Assembly createAssembly() {
        return new Assembly();
    }

    /**
     * Create an instance of {@link ArrayOfCDCustomer }
     * 
     */
    public ArrayOfCDCustomer createArrayOfCDCustomer() {
        return new ArrayOfCDCustomer();
    }

    /**
     * Create an instance of {@link HistoryLog }
     * 
     */
    public HistoryLog createHistoryLog() {
        return new HistoryLog();
    }

    /**
     * Create an instance of {@link BillingAccountLoad }
     * 
     */
    public BillingAccountLoad createBillingAccountLoad() {
        return new BillingAccountLoad();
    }

    /**
     * Create an instance of {@link NodeIdentifier }
     * 
     */
    public NodeIdentifier createNodeIdentifier() {
        return new NodeIdentifier();
    }

    /**
     * Create an instance of {@link AnchorList }
     * 
     */
    public AnchorList createAnchorList() {
        return new AnchorList();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link WaterServiceLocation }
     * 
     */
    public WaterServiceLocation createWaterServiceLocation() {
        return new WaterServiceLocation();
    }

    /**
     * Create an instance of {@link InHomeDisplay }
     * 
     */
    public InHomeDisplay createInHomeDisplay() {
        return new InHomeDisplay();
    }

    /**
     * Create an instance of {@link BillingDetail }
     * 
     */
    public BillingDetail createBillingDetail() {
        return new BillingDetail();
    }

    /**
     * Create an instance of {@link CoordinatesType }
     * 
     */
    public CoordinatesType createCoordinatesType() {
        return new CoordinatesType();
    }

    /**
     * Create an instance of {@link JobWorked }
     * 
     */
    public JobWorked createJobWorked() {
        return new JobWorked();
    }

    /**
     * Create an instance of {@link TestedElectricMeter }
     * 
     */
    public TestedElectricMeter createTestedElectricMeter() {
        return new TestedElectricMeter();
    }

    /**
     * Create an instance of {@link ReceivedElectricMeter }
     * 
     */
    public ReceivedElectricMeter createReceivedElectricMeter() {
        return new ReceivedElectricMeter();
    }

    /**
     * Create an instance of {@link AVLAddress }
     * 
     */
    public AVLAddress createAVLAddress() {
        return new AVLAddress();
    }

    /**
     * Create an instance of {@link GpsLocation }
     * 
     */
    public GpsLocation createGpsLocation() {
        return new GpsLocation();
    }

    /**
     * Create an instance of {@link SecondaryJunctionBox }
     * 
     */
    public SecondaryJunctionBox createSecondaryJunctionBox() {
        return new SecondaryJunctionBox();
    }

    /**
     * Create an instance of {@link MeterConnectivity }
     * 
     */
    public MeterConnectivity createMeterConnectivity() {
        return new MeterConnectivity();
    }

    /**
     * Create an instance of {@link ChargeableDeviceList }
     * 
     */
    public ChargeableDeviceList createChargeableDeviceList() {
        return new ChargeableDeviceList();
    }

    /**
     * Create an instance of {@link ArrayOfGenericPointFeature }
     * 
     */
    public ArrayOfGenericPointFeature createArrayOfGenericPointFeature() {
        return new ArrayOfGenericPointFeature();
    }

    /**
     * Create an instance of {@link PpmBalanceAdjustment }
     * 
     */
    public PpmBalanceAdjustment createPpmBalanceAdjustment() {
        return new PpmBalanceAdjustment();
    }

    /**
     * Create an instance of {@link PointType }
     * 
     */
    public PointType createPointType() {
        return new PointType();
    }

    /**
     * Create an instance of {@link ArrayOfMeterReading }
     * 
     */
    public ArrayOfMeterReading createArrayOfMeterReading() {
        return new ArrayOfMeterReading();
    }

    /**
     * Create an instance of {@link AssemblyList }
     * 
     */
    public AssemblyList createAssemblyList() {
        return new AssemblyList();
    }

    /**
     * Create an instance of {@link MspOverCurrentDeviceList }
     * 
     */
    public MspOverCurrentDeviceList createMspOverCurrentDeviceList() {
        return new MspOverCurrentDeviceList();
    }

    /**
     * Create an instance of {@link InHomeDisplayExchange }
     * 
     */
    public InHomeDisplayExchange createInHomeDisplayExchange() {
        return new InHomeDisplayExchange();
    }

    /**
     * Create an instance of {@link PickListItem }
     * 
     */
    public PickListItem createPickListItem() {
        return new PickListItem();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link GPS }
     * 
     */
    public GPS createGPS() {
        return new GPS();
    }

    /**
     * Create an instance of {@link FlowDemand }
     * 
     */
    public FlowDemand createFlowDemand() {
        return new FlowDemand();
    }

    /**
     * Create an instance of {@link ArrayOfBackSpan }
     * 
     */
    public ArrayOfBackSpan createArrayOfBackSpan() {
        return new ArrayOfBackSpan();
    }

    /**
     * Create an instance of {@link InstrumentTransformers }
     * 
     */
    public InstrumentTransformers createInstrumentTransformers() {
        return new InstrumentTransformers();
    }

    /**
     * Create an instance of {@link Summation }
     * 
     */
    public Summation createSummation() {
        return new Summation();
    }

    /**
     * Create an instance of {@link FeederObject }
     * 
     */
    public FeederObject createFeederObject() {
        return new FeederObject();
    }

    /**
     * Create an instance of {@link MeasurementType }
     * 
     */
    public MeasurementType createMeasurementType() {
        return new MeasurementType();
    }

    /**
     * Create an instance of {@link Registers }
     * 
     */
    public Registers createRegisters() {
        return new Registers();
    }

    /**
     * Create an instance of {@link PayableItem }
     * 
     */
    public PayableItem createPayableItem() {
        return new PayableItem();
    }

    /**
     * Create an instance of {@link ReadingValue }
     * 
     */
    public ReadingValue createReadingValue() {
        return new ReadingValue();
    }

    /**
     * Create an instance of {@link PhysicalObjectList }
     * 
     */
    public PhysicalObjectList createPhysicalObjectList() {
        return new PhysicalObjectList();
    }

    /**
     * Create an instance of {@link ConnectDisconnectList }
     * 
     */
    public ConnectDisconnectList createConnectDisconnectList() {
        return new ConnectDisconnectList();
    }

    /**
     * Create an instance of {@link WorkOrder }
     * 
     */
    public WorkOrder createWorkOrder() {
        return new WorkOrder();
    }

    /**
     * Create an instance of {@link ArrayOfProfileType }
     * 
     */
    public ArrayOfProfileType createArrayOfProfileType() {
        return new ArrayOfProfileType();
    }

    /**
     * Create an instance of {@link Parcel }
     * 
     */
    public Parcel createParcel() {
        return new Parcel();
    }

    /**
     * Create an instance of {@link MeterExchange }
     * 
     */
    public MeterExchange createMeterExchange() {
        return new MeterExchange();
    }

    /**
     * Create an instance of {@link LoggedODEventList }
     * 
     */
    public LoggedODEventList createLoggedODEventList() {
        return new LoggedODEventList();
    }

    /**
     * Create an instance of {@link ArrayOfCapacitor }
     * 
     */
    public ArrayOfCapacitor createArrayOfCapacitor() {
        return new ArrayOfCapacitor();
    }

    /**
     * Create an instance of {@link AsLeft }
     * 
     */
    public AsLeft createAsLeft() {
        return new AsLeft();
    }

    /**
     * Create an instance of {@link GenericPointFeature }
     * 
     */
    public GenericPointFeature createGenericPointFeature() {
        return new GenericPointFeature();
    }

    /**
     * Create an instance of {@link PolygonType }
     * 
     */
    public PolygonType createPolygonType() {
        return new PolygonType();
    }

    /**
     * Create an instance of {@link OutageDetectionLog }
     * 
     */
    public OutageDetectionLog createOutageDetectionLog() {
        return new OutageDetectionLog();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link MessageList }
     * 
     */
    public MessageList createMessageList() {
        return new MessageList();
    }

    /**
     * Create an instance of {@link EaLoc }
     * 
     */
    public EaLoc createEaLoc() {
        return new EaLoc();
    }

    /**
     * Create an instance of {@link ArrayOfSource }
     * 
     */
    public ArrayOfSource createArrayOfSource() {
        return new ArrayOfSource();
    }

    /**
     * Create an instance of {@link Regulator }
     * 
     */
    public Regulator createRegulator() {
        return new Regulator();
    }

    /**
     * Create an instance of {@link BackSpan }
     * 
     */
    public BackSpan createBackSpan() {
        return new BackSpan();
    }

    /**
     * Create an instance of {@link MspLoadGroup }
     * 
     */
    public MspLoadGroup createMspLoadGroup() {
        return new MspLoadGroup();
    }

    /**
     * Create an instance of {@link Riser }
     * 
     */
    public Riser createRiser() {
        return new Riser();
    }

    /**
     * Create an instance of {@link CDDeviceExchange }
     * 
     */
    public CDDeviceExchange createCDDeviceExchange() {
        return new CDDeviceExchange();
    }

    /**
     * Create an instance of {@link InnerBoundaryIs }
     * 
     */
    public InnerBoundaryIs createInnerBoundaryIs() {
        return new InnerBoundaryIs();
    }

    /**
     * Create an instance of {@link ChannelBlock }
     * 
     */
    public ChannelBlock createChannelBlock() {
        return new ChannelBlock();
    }

    /**
     * Create an instance of {@link Truck }
     * 
     */
    public Truck createTruck() {
        return new Truck();
    }

    /**
     * Create an instance of {@link ElectricServiceLocation }
     * 
     */
    public ElectricServiceLocation createElectricServiceLocation() {
        return new ElectricServiceLocation();
    }

    /**
     * Create an instance of {@link ArrayOfChannel }
     * 
     */
    public ArrayOfChannel createArrayOfChannel() {
        return new ArrayOfChannel();
    }

    /**
     * Create an instance of {@link ShortCircuitAnalysisResult }
     * 
     */
    public ShortCircuitAnalysisResult createShortCircuitAnalysisResult() {
        return new ShortCircuitAnalysisResult();
    }

    /**
     * Create an instance of {@link ArrayOfRegulator }
     * 
     */
    public ArrayOfRegulator createArrayOfRegulator() {
        return new ArrayOfRegulator();
    }

    /**
     * Create an instance of {@link OutageDurationEvent }
     * 
     */
    public OutageDurationEvent createOutageDurationEvent() {
        return new OutageDurationEvent();
    }

    /**
     * Create an instance of {@link CallBackList }
     * 
     */
    public CallBackList createCallBackList() {
        return new CallBackList();
    }

    /**
     * Create an instance of {@link SwitchDeviceBank }
     * 
     */
    public SwitchDeviceBank createSwitchDeviceBank() {
        return new SwitchDeviceBank();
    }

    /**
     * Create an instance of {@link WorkTicket }
     * 
     */
    public WorkTicket createWorkTicket() {
        return new WorkTicket();
    }

    /**
     * Create an instance of {@link GenericAnnotationFeature }
     * 
     */
    public GenericAnnotationFeature createGenericAnnotationFeature() {
        return new GenericAnnotationFeature();
    }

    /**
     * Create an instance of {@link DisplayFormat }
     * 
     */
    public DisplayFormat createDisplayFormat() {
        return new DisplayFormat();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link TestInstance }
     * 
     */
    public TestInstance createTestInstance() {
        return new TestInstance();
    }

    /**
     * Create an instance of {@link PropaneUtilityInfo }
     * 
     */
    public PropaneUtilityInfo createPropaneUtilityInfo() {
        return new PropaneUtilityInfo();
    }

    /**
     * Create an instance of {@link ConnectDisconnectEvent }
     * 
     */
    public ConnectDisconnectEvent createConnectDisconnectEvent() {
        return new ConnectDisconnectEvent();
    }

    /**
     * Create an instance of {@link CDDevice }
     * 
     */
    public CDDevice createCDDevice() {
        return new CDDevice();
    }

    /**
     * Create an instance of {@link ServiceLocationList }
     * 
     */
    public ServiceLocationList createServiceLocationList() {
        return new ServiceLocationList();
    }

    /**
     * Create an instance of {@link EmployeeTimeRecord }
     * 
     */
    public EmployeeTimeRecord createEmployeeTimeRecord() {
        return new EmployeeTimeRecord();
    }

    /**
     * Create an instance of {@link ArrayOfGenericLineFeature }
     * 
     */
    public ArrayOfGenericLineFeature createArrayOfGenericLineFeature() {
        return new ArrayOfGenericLineFeature();
    }

    /**
     * Create an instance of {@link UsageItemList }
     * 
     */
    public UsageItemList createUsageItemList() {
        return new UsageItemList();
    }

    /**
     * Create an instance of {@link CustomerCall }
     * 
     */
    public CustomerCall createCustomerCall() {
        return new CustomerCall();
    }

    /**
     * Create an instance of {@link FakeNodeSection }
     * 
     */
    public FakeNodeSection createFakeNodeSection() {
        return new FakeNodeSection();
    }

    /**
     * Create an instance of {@link WaterNameplate }
     * 
     */
    public WaterNameplate createWaterNameplate() {
        return new WaterNameplate();
    }

    /**
     * Create an instance of {@link CircuitElement }
     * 
     */
    public CircuitElement createCircuitElement() {
        return new CircuitElement();
    }

    /**
     * Create an instance of {@link AffectedMeters }
     * 
     */
    public AffectedMeters createAffectedMeters() {
        return new AffectedMeters();
    }

    /**
     * Create an instance of {@link Usage }
     * 
     */
    public Usage createUsage() {
        return new Usage();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link ComplexNum }
     * 
     */
    public ComplexNum createComplexNum() {
        return new ComplexNum();
    }

    /**
     * Create an instance of {@link ExtensionsItem }
     * 
     */
    public ExtensionsItem createExtensionsItem() {
        return new ExtensionsItem();
    }

    /**
     * Create an instance of {@link EMailAddress }
     * 
     */
    public EMailAddress createEMailAddress() {
        return new EMailAddress();
    }

    /**
     * Create an instance of {@link OutageDetectionEvent }
     * 
     */
    public OutageDetectionEvent createOutageDetectionEvent() {
        return new OutageDetectionEvent();
    }

    /**
     * Create an instance of {@link WaterUtilityInfo }
     * 
     */
    public WaterUtilityInfo createWaterUtilityInfo() {
        return new WaterUtilityInfo();
    }

    /**
     * Create an instance of {@link OutageDetectionDevice }
     * 
     */
    public OutageDetectionDevice createOutageDetectionDevice() {
        return new OutageDetectionDevice();
    }

    /**
     * Create an instance of {@link AVLEvent }
     * 
     */
    public AVLEvent createAVLEvent() {
        return new AVLEvent();
    }

    /**
     * Create an instance of {@link Nameplate }
     * 
     */
    public Nameplate createNameplate() {
        return new Nameplate();
    }

    /**
     * Create an instance of {@link LaborCategory }
     * 
     */
    public LaborCategory createLaborCategory() {
        return new LaborCategory();
    }

    /**
     * Create an instance of {@link OutageEvent }
     * 
     */
    public OutageEvent createOutageEvent() {
        return new OutageEvent();
    }

    /**
     * Create an instance of {@link WorkOrderSelection }
     * 
     */
    public WorkOrderSelection createWorkOrderSelection() {
        return new WorkOrderSelection();
    }

    /**
     * Create an instance of {@link LineStringType }
     * 
     */
    public LineStringType createLineStringType() {
        return new LineStringType();
    }

    /**
     * Create an instance of {@link UgPrimaryLine }
     * 
     */
    public UgPrimaryLine createUgPrimaryLine() {
        return new UgPrimaryLine();
    }

    /**
     * Create an instance of {@link ModuleList }
     * 
     */
    public ModuleList createModuleList() {
        return new ModuleList();
    }

    /**
     * Create an instance of {@link MeasurementDevice }
     * 
     */
    public MeasurementDevice createMeasurementDevice() {
        return new MeasurementDevice();
    }

    /**
     * Create an instance of {@link ArrayOfJobWorked }
     * 
     */
    public ArrayOfJobWorked createArrayOfJobWorked() {
        return new ArrayOfJobWorked();
    }

    /**
     * Create an instance of {@link ArrayOfFeederObject }
     * 
     */
    public ArrayOfFeederObject createArrayOfFeederObject() {
        return new ArrayOfFeederObject();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link Telemetry }
     * 
     */
    public Telemetry createTelemetry() {
        return new Telemetry();
    }

    /**
     * Create an instance of {@link MaterialItem }
     * 
     */
    public MaterialItem createMaterialItem() {
        return new MaterialItem();
    }

    /**
     * Create an instance of {@link FixedChargeCodeList }
     * 
     */
    public FixedChargeCodeList createFixedChargeCodeList() {
        return new FixedChargeCodeList();
    }

    /**
     * Create an instance of {@link PpmLocation }
     * 
     */
    public PpmLocation createPpmLocation() {
        return new PpmLocation();
    }

    /**
     * Create an instance of {@link CoordType }
     * 
     */
    public CoordType createCoordType() {
        return new CoordType();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Guy }
     * 
     */
    public Guy createGuy() {
        return new Guy();
    }

    /**
     * Create an instance of {@link ArrayOfGenericAnnotationFeature }
     * 
     */
    public ArrayOfGenericAnnotationFeature createArrayOfGenericAnnotationFeature() {
        return new ArrayOfGenericAnnotationFeature();
    }

    /**
     * Create an instance of {@link PremiseList }
     * 
     */
    public PremiseList createPremiseList() {
        return new PremiseList();
    }

    /**
     * Create an instance of {@link DomainMember }
     * 
     */
    public DomainMember createDomainMember() {
        return new DomainMember();
    }

    /**
     * Create an instance of {@link Crew }
     * 
     */
    public Crew createCrew() {
        return new Crew();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link GasMeter }
     * 
     */
    public GasMeter createGasMeter() {
        return new GasMeter();
    }

    /**
     * Create an instance of {@link Fuse }
     * 
     */
    public Fuse createFuse() {
        return new Fuse();
    }

    /**
     * Create an instance of {@link PropaneServiceLocation }
     * 
     */
    public PropaneServiceLocation createPropaneServiceLocation() {
        return new PropaneServiceLocation();
    }

    /**
     * Create an instance of {@link WaterMeter }
     * 
     */
    public WaterMeter createWaterMeter() {
        return new WaterMeter();
    }

    /**
     * Create an instance of {@link OvercurrentDeviceBank }
     * 
     */
    public OvercurrentDeviceBank createOvercurrentDeviceBank() {
        return new OvercurrentDeviceBank();
    }

    /**
     * Create an instance of {@link UgSecondaryLine }
     * 
     */
    public UgSecondaryLine createUgSecondaryLine() {
        return new UgSecondaryLine();
    }

    /**
     * Create an instance of {@link Recloser }
     * 
     */
    public Recloser createRecloser() {
        return new Recloser();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Tender }
     * 
     */
    public Tender createTender() {
        return new Tender();
    }

    /**
     * Create an instance of {@link PremiseService }
     * 
     */
    public PremiseService createPremiseService() {
        return new PremiseService();
    }

    /**
     * Create an instance of {@link LinearRingType }
     * 
     */
    public LinearRingType createLinearRingType() {
        return new LinearRingType();
    }

    /**
     * Create an instance of {@link ChargeItem }
     * 
     */
    public ChargeItem createChargeItem() {
        return new ChargeItem();
    }

    /**
     * Create an instance of {@link GenericPolygonFeature }
     * 
     */
    public GenericPolygonFeature createGenericPolygonFeature() {
        return new GenericPolygonFeature();
    }

    /**
     * Create an instance of {@link TOUReading }
     * 
     */
    public TOUReading createTOUReading() {
        return new TOUReading();
    }

    /**
     * Create an instance of {@link Conductor }
     * 
     */
    public Conductor createConductor() {
        return new Conductor();
    }

    /**
     * Create an instance of {@link ProfileObject }
     * 
     */
    public ProfileObject createProfileObject() {
        return new ProfileObject();
    }

    /**
     * Create an instance of {@link Capacitor }
     * 
     */
    public Capacitor createCapacitor() {
        return new Capacitor();
    }

    /**
     * Create an instance of {@link CDStateChange }
     * 
     */
    public CDStateChange createCDStateChange() {
        return new CDStateChange();
    }

    /**
     * Create an instance of {@link Anchor }
     * 
     */
    public Anchor createAnchor() {
        return new Anchor();
    }

    /**
     * Create an instance of {@link MspSwitchingDevice }
     * 
     */
    public MspSwitchingDevice createMspSwitchingDevice() {
        return new MspSwitchingDevice();
    }

    /**
     * Create an instance of {@link ArrayOfUsageInstance }
     * 
     */
    public ArrayOfUsageInstance createArrayOfUsageInstance() {
        return new ArrayOfUsageInstance();
    }

    /**
     * Create an instance of {@link UsageInstance }
     * 
     */
    public UsageInstance createUsageInstance() {
        return new UsageInstance();
    }

    /**
     * Create an instance of {@link GasUtilityInfo }
     * 
     */
    public GasUtilityInfo createGasUtilityInfo() {
        return new GasUtilityInfo();
    }

    /**
     * Create an instance of {@link CustomersAttachedToDevice }
     * 
     */
    public CustomersAttachedToDevice createCustomersAttachedToDevice() {
        return new CustomersAttachedToDevice();
    }

    /**
     * Create an instance of {@link Breaker }
     * 
     */
    public Breaker createBreaker() {
        return new Breaker();
    }

    /**
     * Create an instance of {@link CPR }
     * 
     */
    public CPR createCPR() {
        return new CPR();
    }

    /**
     * Create an instance of {@link MeterTestList }
     * 
     */
    public MeterTestList createMeterTestList() {
        return new MeterTestList();
    }

    /**
     * Create an instance of {@link RegulatorBank }
     * 
     */
    public RegulatorBank createRegulatorBank() {
        return new RegulatorBank();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link Pole }
     * 
     */
    public Pole createPole() {
        return new Pole();
    }

    /**
     * Create an instance of {@link ArrayOfChannelBlock }
     * 
     */
    public ArrayOfChannelBlock createArrayOfChannelBlock() {
        return new ArrayOfChannelBlock();
    }

    /**
     * Create an instance of {@link ScadaStatus }
     * 
     */
    public ScadaStatus createScadaStatus() {
        return new ScadaStatus();
    }

    /**
     * Create an instance of {@link Substation }
     * 
     */
    public Substation createSubstation() {
        return new Substation();
    }

    /**
     * Create an instance of {@link ArrayOfEmployee }
     * 
     */
    public ArrayOfEmployee createArrayOfEmployee() {
        return new ArrayOfEmployee();
    }

    /**
     * Create an instance of {@link ArrayOfLaborComponent }
     * 
     */
    public ArrayOfLaborComponent createArrayOfLaborComponent() {
        return new ArrayOfLaborComponent();
    }

    /**
     * Create an instance of {@link AffectedMeter }
     * 
     */
    public AffectedMeter createAffectedMeter() {
        return new AffectedMeter();
    }

    /**
     * Create an instance of {@link Sectionalizer }
     * 
     */
    public Sectionalizer createSectionalizer() {
        return new Sectionalizer();
    }

    /**
     * Create an instance of {@link ChargeItemList }
     * 
     */
    public ChargeItemList createChargeItemList() {
        return new ChargeItemList();
    }

    /**
     * Create an instance of {@link PowerMonitor }
     * 
     */
    public PowerMonitor createPowerMonitor() {
        return new PowerMonitor();
    }

    /**
     * Create an instance of {@link GasServiceLocation }
     * 
     */
    public GasServiceLocation createGasServiceLocation() {
        return new GasServiceLocation();
    }

    /**
     * Create an instance of {@link ArrayOfConductor }
     * 
     */
    public ArrayOfConductor createArrayOfConductor() {
        return new ArrayOfConductor();
    }

    /**
     * Create an instance of {@link CrewActionEvent }
     * 
     */
    public CrewActionEvent createCrewActionEvent() {
        return new CrewActionEvent();
    }

    /**
     * Create an instance of {@link Meter }
     * 
     */
    public Meter createMeter() {
        return new Meter();
    }

    /**
     * Create an instance of {@link StreetLight }
     * 
     */
    public StreetLight createStreetLight() {
        return new StreetLight();
    }

    /**
     * Create an instance of {@link Equipment }
     * 
     */
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link PropaneMeter }
     * 
     */
    public PropaneMeter createPropaneMeter() {
        return new PropaneMeter();
    }

    /**
     * Create an instance of {@link ArrayOfEvent }
     * 
     */
    public ArrayOfEvent createArrayOfEvent() {
        return new ArrayOfEvent();
    }

    /**
     * Create an instance of {@link ArrayOfGraphicSymbol }
     * 
     */
    public ArrayOfGraphicSymbol createArrayOfGraphicSymbol() {
        return new ArrayOfGraphicSymbol();
    }

    /**
     * Create an instance of {@link ArrayOfScadaPoint }
     * 
     */
    public ArrayOfScadaPoint createArrayOfScadaPoint() {
        return new ArrayOfScadaPoint();
    }

    /**
     * Create an instance of {@link MeterTest }
     * 
     */
    public MeterTest createMeterTest() {
        return new MeterTest();
    }

    /**
     * Create an instance of {@link ElectricNameplate }
     * 
     */
    public ElectricNameplate createElectricNameplate() {
        return new ElectricNameplate();
    }

    /**
     * Create an instance of {@link SpanGuy }
     * 
     */
    public SpanGuy createSpanGuy() {
        return new SpanGuy();
    }

    /**
     * Create an instance of {@link PickList }
     * 
     */
    public PickList createPickList() {
        return new PickList();
    }

    /**
     * Create an instance of {@link ScadaAnalog }
     * 
     */
    public ScadaAnalog createScadaAnalog() {
        return new ScadaAnalog();
    }

    /**
     * Create an instance of {@link TimePeriod }
     * 
     */
    public TimePeriod createTimePeriod() {
        return new TimePeriod();
    }

    /**
     * Create an instance of {@link LaborComponent }
     * 
     */
    public LaborComponent createLaborComponent() {
        return new LaborComponent();
    }

    /**
     * Create an instance of {@link ArrayOfTruck }
     * 
     */
    public ArrayOfTruck createArrayOfTruck() {
        return new ArrayOfTruck();
    }

    /**
     * Create an instance of {@link BilledUsage }
     * 
     */
    public BilledUsage createBilledUsage() {
        return new BilledUsage();
    }

    /**
     * Create an instance of {@link BillingData }
     * 
     */
    public BillingData createBillingData() {
        return new BillingData();
    }

    /**
     * Create an instance of {@link OuterBoundaryIs }
     * 
     */
    public OuterBoundaryIs createOuterBoundaryIs() {
        return new OuterBoundaryIs();
    }

    /**
     * Create an instance of {@link MeterGroup }
     * 
     */
    public MeterGroup createMeterGroup() {
        return new MeterGroup();
    }

    /**
     * Create an instance of {@link LoadSection }
     * 
     */
    public LoadSection createLoadSection() {
        return new LoadSection();
    }

    /**
     * Create an instance of {@link CabinetContentsList }
     * 
     */
    public CabinetContentsList createCabinetContentsList() {
        return new CabinetContentsList();
    }

    /**
     * Create an instance of {@link ScadaPoints }
     * 
     */
    public ScadaPoints createScadaPoints() {
        return new ScadaPoints();
    }

    /**
     * Create an instance of {@link WarehouseLocation }
     * 
     */
    public WarehouseLocation createWarehouseLocation() {
        return new WarehouseLocation();
    }

    /**
     * Create an instance of {@link ArrayOfAllocatedLoad }
     * 
     */
    public ArrayOfAllocatedLoad createArrayOfAllocatedLoad() {
        return new ArrayOfAllocatedLoad();
    }

    /**
     * Create an instance of {@link Transformer }
     * 
     */
    public Transformer createTransformer() {
        return new Transformer();
    }

    /**
     * Create an instance of {@link Generator }
     * 
     */
    public Generator createGenerator() {
        return new Generator();
    }

    /**
     * Create an instance of {@link MaterialComponent }
     * 
     */
    public MaterialComponent createMaterialComponent() {
        return new MaterialComponent();
    }

    /**
     * Create an instance of {@link MeterReading }
     * 
     */
    public MeterReading createMeterReading() {
        return new MeterReading();
    }

    /**
     * Create an instance of {@link CapacitorBank }
     * 
     */
    public CapacitorBank createCapacitorBank() {
        return new CapacitorBank();
    }

    /**
     * Create an instance of {@link PowerSystemDevice }
     * 
     */
    public PowerSystemDevice createPowerSystemDevice() {
        return new PowerSystemDevice();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link CustomersAffectedByOutage }
     * 
     */
    public CustomersAffectedByOutage createCustomersAffectedByOutage() {
        return new CustomersAffectedByOutage();
    }

    /**
     * Create an instance of {@link ArrayOfMaterialComponent }
     * 
     */
    public ArrayOfMaterialComponent createArrayOfMaterialComponent() {
        return new ArrayOfMaterialComponent();
    }

    /**
     * Create an instance of {@link OhPrimaryLine }
     * 
     */
    public OhPrimaryLine createOhPrimaryLine() {
        return new OhPrimaryLine();
    }

    /**
     * Create an instance of {@link MeterList }
     * 
     */
    public MeterList createMeterList() {
        return new MeterList();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link ArrayOfWarehouseLocation }
     * 
     */
    public ArrayOfWarehouseLocation createArrayOfWarehouseLocation() {
        return new ArrayOfWarehouseLocation();
    }

    /**
     * Create an instance of {@link PowerFactorManagementEvent }
     * 
     */
    public PowerFactorManagementEvent createPowerFactorManagementEvent() {
        return new PowerFactorManagementEvent();
    }

    /**
     * Create an instance of {@link SpatialFeatureGroup }
     * 
     */
    public SpatialFeatureGroup createSpatialFeatureGroup() {
        return new SpatialFeatureGroup();
    }

    /**
     * Create an instance of {@link ObjectRef }
     * 
     */
    public ObjectRef createObjectRef() {
        return new ObjectRef();
    }

    /**
     * Create an instance of {@link LoadManagementDevice }
     * 
     */
    public LoadManagementDevice createLoadManagementDevice() {
        return new LoadManagementDevice();
    }

    /**
     * Create an instance of {@link GraphicSymbol }
     * 
     */
    public GraphicSymbol createGraphicSymbol() {
        return new GraphicSymbol();
    }

    /**
     * Create an instance of {@link MspSwitchDeviceList }
     * 
     */
    public MspSwitchDeviceList createMspSwitchDeviceList() {
        return new MspSwitchDeviceList();
    }

    /**
     * Create an instance of {@link LoggedOutageDetectionEvent }
     * 
     */
    public LoggedOutageDetectionEvent createLoggedOutageDetectionEvent() {
        return new LoggedOutageDetectionEvent();
    }

    /**
     * Create an instance of {@link ArrayOfEquipment }
     * 
     */
    public ArrayOfEquipment createArrayOfEquipment() {
        return new ArrayOfEquipment();
    }

    /**
     * Create an instance of {@link Timesheet }
     * 
     */
    public Timesheet createTimesheet() {
        return new Timesheet();
    }

    /**
     * Create an instance of {@link AsFound }
     * 
     */
    public AsFound createAsFound() {
        return new AsFound();
    }

    /**
     * Create an instance of {@link CoincidentalValue }
     * 
     */
    public CoincidentalValue createCoincidentalValue() {
        return new CoincidentalValue();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link MeterBase.DeviceList.LoadManagementlDeviceList }
     * 
     */
    public MeterBase.DeviceList.LoadManagementlDeviceList createMeterBaseDeviceListLoadManagementlDeviceList() {
        return new MeterBase.DeviceList.LoadManagementlDeviceList();
    }

    /**
     * Create an instance of {@link EndDeviceShipment.TransponderIDRange }
     * 
     */
    public EndDeviceShipment.TransponderIDRange createEndDeviceShipmentTransponderIDRange() {
        return new EndDeviceShipment.TransponderIDRange();
    }

    /**
     * Create an instance of {@link EndDeviceShipment.ReceivedMeters }
     * 
     */
    public EndDeviceShipment.ReceivedMeters createEndDeviceShipmentReceivedMeters() {
        return new EndDeviceShipment.ReceivedMeters();
    }

    /**
     * Create an instance of {@link EndDeviceShipment.ReceivedModules }
     * 
     */
    public EndDeviceShipment.ReceivedModules createEndDeviceShipmentReceivedModules() {
        return new EndDeviceShipment.ReceivedModules();
    }

    /**
     * Create an instance of {@link EndDeviceShipment.ReceivedLoadManagementDevices }
     * 
     */
    public EndDeviceShipment.ReceivedLoadManagementDevices createEndDeviceShipmentReceivedLoadManagementDevices() {
        return new EndDeviceShipment.ReceivedLoadManagementDevices();
    }

    /**
     * Create an instance of {@link EndDeviceShipment.ReceivedCDDevices }
     * 
     */
    public EndDeviceShipment.ReceivedCDDevices createEndDeviceShipmentReceivedCDDevices() {
        return new EndDeviceShipment.ReceivedCDDevices();
    }

    /**
     * Create an instance of {@link Meters.ElectricMeters }
     * 
     */
    public Meters.ElectricMeters createMetersElectricMeters() {
        return new Meters.ElectricMeters();
    }

    /**
     * Create an instance of {@link Meters.WaterMeters }
     * 
     */
    public Meters.WaterMeters createMetersWaterMeters() {
        return new Meters.WaterMeters();
    }

    /**
     * Create an instance of {@link Meters.GasMeters }
     * 
     */
    public Meters.GasMeters createMetersGasMeters() {
        return new Meters.GasMeters();
    }

    /**
     * Create an instance of {@link Meters.PropaneMeters }
     * 
     */
    public Meters.PropaneMeters createMetersPropaneMeters() {
        return new Meters.PropaneMeters();
    }

    /**
     * Create an instance of {@link SubstationLoadControlStatus.ControlledItems.ControlItem }
     * 
     */
    public SubstationLoadControlStatus.ControlledItems.ControlItem createSubstationLoadControlStatusControlledItemsControlItem() {
        return new SubstationLoadControlStatus.ControlledItems.ControlItem();
    }

    /**
     * Create an instance of {@link LoadManagementEvent.Strategy.ApplicationPointList }
     * 
     */
    public LoadManagementEvent.Strategy.ApplicationPointList createLoadManagementEventStrategyApplicationPointList() {
        return new LoadManagementEvent.Strategy.ApplicationPointList();
    }

    /**
     * Create an instance of {@link com.partnersoft.v5.soap.service.example.multispeak.model.OutageCustomer.TimeToCall }
     * 
     */
    public com.partnersoft.v5.soap.service.example.multispeak.model.OutageCustomer.TimeToCall createOutageCustomerTimeToCall() {
        return new com.partnersoft.v5.soap.service.example.multispeak.model.OutageCustomer.TimeToCall();
    }

    /**
     * Create an instance of {@link ServiceLocation.CalculatedCurrentBillReadings }
     * 
     */
    public ServiceLocation.CalculatedCurrentBillReadings createServiceLocationCalculatedCurrentBillReadings() {
        return new ServiceLocation.CalculatedCurrentBillReadings();
    }

    /**
     * Create an instance of {@link Premise.PremiseServiceList }
     * 
     */
    public Premise.PremiseServiceList createPremisePremiseServiceList() {
        return new Premise.PremiseServiceList();
    }

    /**
     * Create an instance of {@link ServiceLocations.ElectricServiceLocations }
     * 
     */
    public ServiceLocations.ElectricServiceLocations createServiceLocationsElectricServiceLocations() {
        return new ServiceLocations.ElectricServiceLocations();
    }

    /**
     * Create an instance of {@link ServiceLocations.WaterServiceLocations }
     * 
     */
    public ServiceLocations.WaterServiceLocations createServiceLocationsWaterServiceLocations() {
        return new ServiceLocations.WaterServiceLocations();
    }

    /**
     * Create an instance of {@link ServiceLocations.GasServiceLocations }
     * 
     */
    public ServiceLocations.GasServiceLocations createServiceLocationsGasServiceLocations() {
        return new ServiceLocations.GasServiceLocations();
    }

    /**
     * Create an instance of {@link ServiceLocations.PropaneServiceLocations }
     * 
     */
    public ServiceLocations.PropaneServiceLocations createServiceLocationsPropaneServiceLocations() {
        return new ServiceLocations.PropaneServiceLocations();
    }

    /**
     * Create an instance of {@link MeterRead.TOUReadings }
     * 
     */
    public MeterRead.TOUReadings createMeterReadTOUReadings() {
        return new MeterRead.TOUReadings();
    }

    /**
     * Create an instance of {@link MeterRead.ReadingValues }
     * 
     */
    public MeterRead.ReadingValues createMeterReadReadingValues() {
        return new MeterRead.ReadingValues();
    }

    /**
     * Create an instance of {@link PayableItemList.AllowableTransactionTypes }
     * 
     */
    public PayableItemList.AllowableTransactionTypes createPayableItemListAllowableTransactionTypes() {
        return new PayableItemList.AllowableTransactionTypes();
    }

    /**
     * Create an instance of {@link GasNameplate.GasPressure }
     * 
     */
    public GasNameplate.GasPressure createGasNameplateGasPressure() {
        return new GasNameplate.GasPressure();
    }

    /**
     * Create an instance of {@link GasNameplate.GasFlow }
     * 
     */
    public GasNameplate.GasFlow createGasNameplateGasFlow() {
        return new GasNameplate.GasFlow();
    }

    /**
     * Create an instance of {@link LinkedTransformer.UnitList }
     * 
     */
    public LinkedTransformer.UnitList createLinkedTransformerUnitList() {
        return new LinkedTransformer.UnitList();
    }

    /**
     * Create an instance of {@link ContactInfo.PhoneList }
     * 
     */
    public ContactInfo.PhoneList createContactInfoPhoneList() {
        return new ContactInfo.PhoneList();
    }

    /**
     * Create an instance of {@link ContactInfo.EMailList }
     * 
     */
    public ContactInfo.EMailList createContactInfoEMailList() {
        return new ContactInfo.EMailList();
    }

    /**
     * Create an instance of {@link ArrayOfOutageCustomerListOutageCustomer.OutageCustomer }
     * 
     */
    public ArrayOfOutageCustomerListOutageCustomer.OutageCustomer createArrayOfOutageCustomerListOutageCustomerOutageCustomer() {
        return new ArrayOfOutageCustomerListOutageCustomer.OutageCustomer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiSpeakMsgHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "MultiSpeakMsgHeader")
    public JAXBElement<MultiSpeakMsgHeader> createMultiSpeakMsgHeader(MultiSpeakMsgHeader value) {
        return new JAXBElement<MultiSpeakMsgHeader>(_MultiSpeakMsgHeader_QNAME, MultiSpeakMsgHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "parentSectionID", scope = MspConnectivityPoint.class)
    public JAXBElement<ObjectRef> createMspConnectivityPointParentSectionID(ObjectRef value) {
        return new JAXBElement<ObjectRef>(_MspConnectivityPointParentSectionID_QNAME, ObjectRef.class, MspConnectivityPoint.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "toNodeID", scope = MspConnectivityPoint.class)
    public JAXBElement<NodeIdentifier> createMspConnectivityPointToNodeID(NodeIdentifier value) {
        return new JAXBElement<NodeIdentifier>(_MspConnectivityPointToNodeID_QNAME, NodeIdentifier.class, MspConnectivityPoint.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "sectionID", scope = MspConnectivityPoint.class)
    public JAXBElement<String> createMspConnectivityPointSectionID(String value) {
        return new JAXBElement<String>(_MspConnectivityPointSectionID_QNAME, String.class, MspConnectivityPoint.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "fromNodeID", scope = MspConnectivityPoint.class)
    public JAXBElement<NodeIdentifier> createMspConnectivityPointFromNodeID(NodeIdentifier value) {
        return new JAXBElement<NodeIdentifier>(_MspConnectivityPointFromNodeID_QNAME, NodeIdentifier.class, MspConnectivityPoint.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceShipment.ReceivedModules }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "receivedModules", scope = EndDeviceShipment.class)
    public JAXBElement<EndDeviceShipment.ReceivedModules> createEndDeviceShipmentReceivedModules(EndDeviceShipment.ReceivedModules value) {
        return new JAXBElement<EndDeviceShipment.ReceivedModules>(_EndDeviceShipmentReceivedModules_QNAME, EndDeviceShipment.ReceivedModules.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "poReferenceNumber", scope = EndDeviceShipment.class)
    public JAXBElement<String> createEndDeviceShipmentPoReferenceNumber(String value) {
        return new JAXBElement<String>(_EndDeviceShipmentPoReferenceNumber_QNAME, String.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "shippingTicketNumber", scope = EndDeviceShipment.class)
    public JAXBElement<String> createEndDeviceShipmentShippingTicketNumber(String value) {
        return new JAXBElement<String>(_EndDeviceShipmentShippingTicketNumber_QNAME, String.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceShipment.ReceivedMeters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "receivedMeters", scope = EndDeviceShipment.class)
    public JAXBElement<EndDeviceShipment.ReceivedMeters> createEndDeviceShipmentReceivedMeters(EndDeviceShipment.ReceivedMeters value) {
        return new JAXBElement<EndDeviceShipment.ReceivedMeters>(_EndDeviceShipmentReceivedMeters_QNAME, EndDeviceShipment.ReceivedMeters.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "recipient", scope = EndDeviceShipment.class)
    public JAXBElement<String> createEndDeviceShipmentRecipient(String value) {
        return new JAXBElement<String>(_EndDeviceShipmentRecipient_QNAME, String.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "shippedToAddress", scope = EndDeviceShipment.class)
    public JAXBElement<Address> createEndDeviceShipmentShippedToAddress(Address value) {
        return new JAXBElement<Address>(_EndDeviceShipmentShippedToAddress_QNAME, Address.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "utility", scope = EndDeviceShipment.class)
    public JAXBElement<String> createEndDeviceShipmentUtility(String value) {
        return new JAXBElement<String>(_EndDeviceShipmentUtility_QNAME, String.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceShipment.TransponderIDRange }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "transponderIDRange", scope = EndDeviceShipment.class)
    public JAXBElement<EndDeviceShipment.TransponderIDRange> createEndDeviceShipmentTransponderIDRange(EndDeviceShipment.TransponderIDRange value) {
        return new JAXBElement<EndDeviceShipment.TransponderIDRange>(_EndDeviceShipmentTransponderIDRange_QNAME, EndDeviceShipment.TransponderIDRange.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceShipment.ReceivedCDDevices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "receivedCDDevices", scope = EndDeviceShipment.class)
    public JAXBElement<EndDeviceShipment.ReceivedCDDevices> createEndDeviceShipmentReceivedCDDevices(EndDeviceShipment.ReceivedCDDevices value) {
        return new JAXBElement<EndDeviceShipment.ReceivedCDDevices>(_EndDeviceShipmentReceivedCDDevices_QNAME, EndDeviceShipment.ReceivedCDDevices.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceShipment.ReceivedLoadManagementDevices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "receivedLoadManagementDevices", scope = EndDeviceShipment.class)
    public JAXBElement<EndDeviceShipment.ReceivedLoadManagementDevices> createEndDeviceShipmentReceivedLoadManagementDevices(EndDeviceShipment.ReceivedLoadManagementDevices value) {
        return new JAXBElement<EndDeviceShipment.ReceivedLoadManagementDevices>(_EndDeviceShipmentReceivedLoadManagementDevices_QNAME, EndDeviceShipment.ReceivedLoadManagementDevices.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "shippedDate", scope = EndDeviceShipment.class)
    public JAXBElement<XMLGregorianCalendar> createEndDeviceShipmentShippedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EndDeviceShipmentShippedDate_QNAME, XMLGregorianCalendar.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "manufacturer", scope = EndDeviceShipment.class)
    public JAXBElement<String> createEndDeviceShipmentManufacturer(String value) {
        return new JAXBElement<String>(_EndDeviceShipmentManufacturer_QNAME, String.class, EndDeviceShipment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "parentSectionID", scope = MspConnectivityLine.class)
    public JAXBElement<ObjectRef> createMspConnectivityLineParentSectionID(ObjectRef value) {
        return new JAXBElement<ObjectRef>(_MspConnectivityPointParentSectionID_QNAME, ObjectRef.class, MspConnectivityLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "toNodeID", scope = MspConnectivityLine.class)
    public JAXBElement<NodeIdentifier> createMspConnectivityLineToNodeID(NodeIdentifier value) {
        return new JAXBElement<NodeIdentifier>(_MspConnectivityPointToNodeID_QNAME, NodeIdentifier.class, MspConnectivityLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "sectionID", scope = MspConnectivityLine.class)
    public JAXBElement<String> createMspConnectivityLineSectionID(String value) {
        return new JAXBElement<String>(_MspConnectivityPointSectionID_QNAME, String.class, MspConnectivityLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "fromNodeID", scope = MspConnectivityLine.class)
    public JAXBElement<NodeIdentifier> createMspConnectivityLineFromNodeID(NodeIdentifier value) {
        return new JAXBElement<NodeIdentifier>(_MspConnectivityPointFromNodeID_QNAME, NodeIdentifier.class, MspConnectivityLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "clockForward", scope = Status.class)
    public JAXBElement<Boolean> createStatusClockForward(Boolean value) {
        return new JAXBElement<Boolean>(_StatusClockForward_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "testData", scope = Status.class)
    public JAXBElement<Boolean> createStatusTestData(Boolean value) {
        return new JAXBElement<Boolean>(_StatusTestData_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "recorderStopped", scope = Status.class)
    public JAXBElement<Boolean> createStatusRecorderStopped(Boolean value) {
        return new JAXBElement<Boolean>(_StatusRecorderStopped_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "DSTinEffect", scope = Status.class)
    public JAXBElement<Boolean> createStatusDSTinEffect(Boolean value) {
        return new JAXBElement<Boolean>(_StatusDSTinEffect_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "overflow", scope = Status.class)
    public JAXBElement<Boolean> createStatusOverflow(Boolean value) {
        return new JAXBElement<Boolean>(_StatusOverflow_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "invalid", scope = Status.class)
    public JAXBElement<Boolean> createStatusInvalid(Boolean value) {
        return new JAXBElement<Boolean>(_StatusInvalid_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "configChanged", scope = Status.class)
    public JAXBElement<Boolean> createStatusConfigChanged(Boolean value) {
        return new JAXBElement<Boolean>(_StatusConfigChanged_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "manuallyModified", scope = Status.class)
    public JAXBElement<Boolean> createStatusManuallyModified(Boolean value) {
        return new JAXBElement<Boolean>(_StatusManuallyModified_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "clockBackward", scope = Status.class)
    public JAXBElement<Boolean> createStatusClockBackward(Boolean value) {
        return new JAXBElement<Boolean>(_StatusClockBackward_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "manuallyEntered", scope = Status.class)
    public JAXBElement<Boolean> createStatusManuallyEntered(Boolean value) {
        return new JAXBElement<Boolean>(_StatusManuallyEntered_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "partialInterval", scope = Status.class)
    public JAXBElement<Boolean> createStatusPartialInterval(Boolean value) {
        return new JAXBElement<Boolean>(_StatusPartialInterval_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "longInterval", scope = Status.class)
    public JAXBElement<Boolean> createStatusLongInterval(Boolean value) {
        return new JAXBElement<Boolean>(_StatusLongInterval_QNAME, Boolean.class, Status.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "parentSectionID", scope = ElectricServiceLocation.class)
    public JAXBElement<ObjectRef> createElectricServiceLocationParentSectionID(ObjectRef value) {
        return new JAXBElement<ObjectRef>(_MspConnectivityPointParentSectionID_QNAME, ObjectRef.class, ElectricServiceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "toNodeID", scope = ElectricServiceLocation.class)
    public JAXBElement<NodeIdentifier> createElectricServiceLocationToNodeID(NodeIdentifier value) {
        return new JAXBElement<NodeIdentifier>(_MspConnectivityPointToNodeID_QNAME, NodeIdentifier.class, ElectricServiceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "sectionID", scope = ElectricServiceLocation.class)
    public JAXBElement<String> createElectricServiceLocationSectionID(String value) {
        return new JAXBElement<String>(_MspConnectivityPointSectionID_QNAME, String.class, ElectricServiceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "fromNodeID", scope = ElectricServiceLocation.class)
    public JAXBElement<NodeIdentifier> createElectricServiceLocationFromNodeID(NodeIdentifier value) {
        return new JAXBElement<NodeIdentifier>(_MspConnectivityPointFromNodeID_QNAME, NodeIdentifier.class, ElectricServiceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MspSwitchingDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "mspSwitchingDevice", scope = MspSwitchDeviceList.class)
    public JAXBElement<MspSwitchingDevice> createMspSwitchDeviceListMspSwitchingDevice(MspSwitchingDevice value) {
        return new JAXBElement<MspSwitchingDevice>(_MspSwitchDeviceListMspSwitchingDevice_QNAME, MspSwitchingDevice.class, MspSwitchDeviceList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MspOverCurrentDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "mspOverCurrentDevice", scope = MspSwitchDeviceList.class)
    public JAXBElement<MspOverCurrentDevice> createMspSwitchDeviceListMspOverCurrentDevice(MspOverCurrentDevice value) {
        return new JAXBElement<MspOverCurrentDevice>(_MspSwitchDeviceListMspOverCurrentDevice_QNAME, MspOverCurrentDevice.class, MspSwitchDeviceList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MspSwitchingDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.multispeak.org/Version_3.0", name = "switch", scope = MspSwitchDeviceList.class)
    public JAXBElement<MspSwitchingDevice> createMspSwitchDeviceListSwitch(MspSwitchingDevice value) {
        return new JAXBElement<MspSwitchingDevice>(_MspSwitchDeviceListSwitch_QNAME, MspSwitchingDevice.class, MspSwitchDeviceList.class, value);
    }

}
