//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.multispeak.org/Version_3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.partnersoft.v5.soap.service.example.multispeak.model;
