//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ppmMeterExchange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ppmMeterExchange">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_3.0}mspObject">
 *       &lt;sequence>
 *         &lt;element name="ppmLocationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outMeterRead" type="{http://www.multispeak.org/Version_3.0}meterRead" minOccurs="0"/>
 *         &lt;element name="inMeterRead" type="{http://www.multispeak.org/Version_3.0}meterRead" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ppmMeterExchange", propOrder = {
    "ppmLocationID",
    "outMeterRead",
    "inMeterRead"
})
public class PpmMeterExchange
    extends MspObject
{

    protected String ppmLocationID;
    protected MeterRead outMeterRead;
    protected MeterRead inMeterRead;

    /**
     * Gets the value of the ppmLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpmLocationID() {
        return ppmLocationID;
    }

    /**
     * Sets the value of the ppmLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpmLocationID(String value) {
        this.ppmLocationID = value;
    }

    /**
     * Gets the value of the outMeterRead property.
     * 
     * @return
     *     possible object is
     *     {@link MeterRead }
     *     
     */
    public MeterRead getOutMeterRead() {
        return outMeterRead;
    }

    /**
     * Sets the value of the outMeterRead property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeterRead }
     *     
     */
    public void setOutMeterRead(MeterRead value) {
        this.outMeterRead = value;
    }

    /**
     * Gets the value of the inMeterRead property.
     * 
     * @return
     *     possible object is
     *     {@link MeterRead }
     *     
     */
    public MeterRead getInMeterRead() {
        return inMeterRead;
    }

    /**
     * Sets the value of the inMeterRead property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeterRead }
     *     
     */
    public void setInMeterRead(MeterRead value) {
        this.inMeterRead = value;
    }

}
