//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 05:19:04 PM EDT 
//


package com.partnersoft.v5.soap.service.example.multispeak.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propaneMeter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propaneMeter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_3.0}mspMeter">
 *       &lt;sequence>
 *         &lt;element name="propaneNameplate" type="{http://www.multispeak.org/Version_3.0}propaneNameplate" minOccurs="0"/>
 *         &lt;element name="propaneUtilityInfo" type="{http://www.multispeak.org/Version_3.0}propaneUtilityInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propaneMeter", propOrder = {
    "propaneNameplate",
    "propaneUtilityInfo"
})
public class PropaneMeter
    extends MspMeter
{

    protected PropaneNameplate propaneNameplate;
    protected PropaneUtilityInfo propaneUtilityInfo;

    /**
     * Gets the value of the propaneNameplate property.
     * 
     * @return
     *     possible object is
     *     {@link PropaneNameplate }
     *     
     */
    public PropaneNameplate getPropaneNameplate() {
        return propaneNameplate;
    }

    /**
     * Sets the value of the propaneNameplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropaneNameplate }
     *     
     */
    public void setPropaneNameplate(PropaneNameplate value) {
        this.propaneNameplate = value;
    }

    /**
     * Gets the value of the propaneUtilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PropaneUtilityInfo }
     *     
     */
    public PropaneUtilityInfo getPropaneUtilityInfo() {
        return propaneUtilityInfo;
    }

    /**
     * Sets the value of the propaneUtilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropaneUtilityInfo }
     *     
     */
    public void setPropaneUtilityInfo(PropaneUtilityInfo value) {
        this.propaneUtilityInfo = value;
    }

}
